version: '3'
services:


  api_bill:
    build:
      context: .
      dockerfile: docker_config/app/Dockerfile
    container_name: api_bill
    working_dir: /var/www/app
    volumes:
      - ./src:/var/www/app
    networks:
      - yandex_network
    env_file:
      - .env
    depends_on:
      - postgres_bill

  nginx_bill:
    image: nginx:1.21.6-alpine
    container_name: nginx_bill
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker_config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker_config/nginx/service.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api_bill
    networks:
      - yandex_network

  postgres_bill:
    image: postgres:13-alpine
    container_name: postgres_bill
    env_file:
      - .env
    volumes:
      - postgres_bill_data:/var/lib/postgresql/data
    networks:
      - yandex_network

networks:
  yandex_network:
    external: true
volumes:
  postgres_bill_data:

