PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND'
PRODUCT_ALREADY_EXISTS = 'PRODUCT_ALREADY_EXISTS'
PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND'
NOT_DATA_RECURRING = 'Not Data Recurring'
PRICE_NOT_FOUND = 'PRICE_NOT_FOUND'

WH_NOT_VERIFIED = 'Webhook signature is not verified.'
SUCCESS = 'Success'
